baseURL = 'https://amilacg.github.io/'
languageCode = 'en-us'
title = 'Pixels & Pipelines'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = false
[params.assets]
  customCSS = ["css/credit.css"]
